// Legacy icon-name registry — kept as a reference for type-ahead.
// Runtime icon resolution lives in src/components/Icon.tsx, which imports
// icons directly from the @iconify/icons-* npm packages (no local addCollection cache).
export type IconName =
    | "fa6-brands:bilibili"
    | "fa6-brands:github"
    | "fa6-brands:npm"
    | "fa6-solid:arrow-rotate-left"
    | "material-symbols:article-outline-rounded"
    | "material-symbols:calendar-month-outline-rounded"
    | "material-symbols:chevron-right-rounded"
    | "material-symbols:check-rounded"
    | "material-symbols:close-rounded"
    | "material-symbols:content-copy-outline-rounded"
    | "material-symbols:dark-mode-outline-rounded"
    | "material-symbols:download-2-outline-rounded"
    | "material-symbols:download-outline-rounded"
    | "material-symbols:download-rounded"
    | "material-symbols:expand-more-rounded"
    | "material-symbols:folder-outline-rounded"
    | "material-symbols:format-list-numbered-rounded"
    | "material-symbols:home-outline-rounded"
    | "material-symbols:info-outline-rounded"
    | "material-symbols:keyboard-arrow-up-rounded"
    | "material-symbols:magic-button-outline"
    | "material-symbols:mail"
    | "material-symbols:menu-rounded"
    | "material-symbols:palette-outline"
    | "material-symbols:radio-button-partial-outline"
    | "material-symbols:schedule-rounded"
    | "material-symbols:search-rounded"
    | "material-symbols:tag-outline-rounded"
    | "material-symbols:text-fields-rounded"
    | "material-symbols:update-rounded"
    | "material-symbols:wb-sunny-outline-rounded";
